simulation:
  tick_rate: 20
  width: 75
  height: 75
  num_bushes: 50
  num_organisms: 50
  max_ticks: 100
  seed:

master_env:
  width: 30
  height: 30
  num_bushes: 200
  seed:

neat:
  num_gens: 50
  sim_ticks: 500

server:
  host: "127.0.0.1"
  port: 9001
